version: "3.9"

services:
  nestjs-testing:
    image: nestjs-testing:TEST
    container_name: nestjs-testing
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgresql
    networks:
      - my-nw
    environment:
      DATABASE_HOST: postgresql
      DATABASE_PORT: 5432
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: secret
      DATABASE_NAME: mydb-dev

  postgresql:
    image: postgres:12-alpine
    container_name: postgres-dev
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb-dev
    ports:
      - 5432:5432
    networks:
      - my-nw

networks:
  my-nw:
    driver: bridge
