name: Test

on:
  push:
    branches: [main]

jobs:
  container-job:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}      
      - name: Install dependencies
        run: npm ci
      - name: run unit tests
        run: npm run test:cov
      - name: run e2e tests
        run: npm run test:e2e
