name: Test

on:
  push:
    branches: [main]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}      
      - name: Install dependencies
        run: npm ci
      - name: run unit tests
        run: npm run test:cov
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Startup Integration Environment
        run: docker-compose -f ./docker-compose.yml up -d
       - name: Waiting for Starting Integration Environment
        run: sleep 30
      - name: Shutdown Integration Environment
        if: always()
        run: docker-compose -f ./docker-compose.yml down --volumes
      - name: Clean up Docker images
        if: always()
        run: docker rmi sample-api:TEST
        continue-on-error: true               
