name: Test

on:
  push:
    branches: [main]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: node-modules-${{ hashFiles('**/package-lock.json') }}      

      - name: Install dependencies
        run: npm ci

      - name: run unit tests
        run: npm run test:cov

  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Startup Integration Environment
        run: docker-compose up -d

       - name: Waiting for Starting Integration Environment
        run: sleep 30

      - name: Clean up Docker images
        if: always()
        run: docker-compose down --rmi all --volumes
        continue-on-error: true               
